[flavor]
light = "catppuccin-latte"
dark = "catppuccin-mocha"

[icon]

prepend_conds = [
  { if = "link", text = "" },  # Normal files (not directories or symlinks)
  { if = "dir",           text = "" },  # Directories
]
